### ISSUE TITLE
Can't update existing record due to missing method

### ISSUE THREAD

**Issue by ryanwilliams** [tarolandia/cassandro#2]
Hi

When I try to save an existing record by doing "foo.save" it fails with this error:

    NoMethodError: undefined method `metadata' for #<Cassandra::Statements::Prepared:0x000001089c2850>
        from /Users/ryanwilliams/.rvm/gems/ruby-2.1.2/gems/cassandro-1.0.3/lib/cassandro/model.rb:291:in `statement_for'
        from /Users/ryanwilliams/.rvm/gems/ruby-2.1.2/gems/cassandro-1.0.3/lib/cassandro/model.rb:100:in `save'

Seems like a bug to me. Perhaps the wrong version of ruby-driver?

**Comment by tarolandia** [comment]
hi @ryanwilliams 

could you copy the full example code? I will try to reproduce it locally and fix it.

In the meanwhile I updated `.gems` file with last version of `cassandra-driver`. Which version are you using?

**Comment by ryanwilliams** [comment]
It happens if you call 'foo.save' multiple times. Even with the example code from the readme.

**Comment by tarolandia** [comment]
I will take a look. Thanks for testing it!

**Comment by tarolandia** [comment]
@ryanwilliams Good catch! I pushed `cassandro 1.0.4` with this problem fixed.
Thank you very much.

**Comment by tarolandia** [comment]
__Update__:

This bug was caused by a change of attribute name on a `cassandra-driver` class.

@ryanwilliams FYI there is another method of updating attributes on `cassandro`

```ruby
person = Person.create(
  name: 'Monkey',
  age: 29,
  address: 'Banana Tree 123'
)

person.update_attributes(age: 30, address: 'Banana Road 321')
```
